export const ANIMATION_CONFIG = {
  HERO_ROTATION_INTERVAL: 5000,
  WORD_ANIMATION_DELAY: 0.15,
  TITLE_ANIMATION_DELAY: 300,
  TRANSITION_DURATION: 800,
  LERP_AMOUNT: 0.2,
} as const;

export const HERO_ANIMATION = {
  WELCOME_TEXT_START_DELAY: 0,
  TITLE_LINE_1_START_DELAY: 0.6,
  TITLE_LINE_2_START_DELAY: 1.05,
} as const;

export const CAROUSEL_CONFIG = {
  MOUSE_SENSITIVITY: 30,
  TOUCH_SENSITIVITY: 10,
  BOUNDARY_OFFSET: 3,
} as const;
